# Generated by Django 5.2.8 on 2025-12-02 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(max_length=100)),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo_url', models.URLField(blank=True, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('location_raw', models.CharField(blank=True, max_length=200, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_state', models.CharField(blank=True, max_length=100, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('salary_period', models.CharField(blank=True, max_length=20, null=True)),
                ('job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_address', models.TextField(blank=True, null=True)),
                ('geo_latitude', models.FloatField(blank=True, null=True)),
                ('geo_longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('original_payload', models.JSONField(blank=True, null=True)),
                ('source_metadata', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('times_seen', models.IntegerField(default=1)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
