# Generated by Django 5.2.8 on 2025-12-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_at',
            field=models.CharField(blank=True, null=True),
        ),
    ]
